version: '3.8'

services:
  # 1. Baza danych MySQL
  mysql-db:
    image: mysql:8.0
    container_name: quiz-mysql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "bardzo_silne_haslo_123"
      MYSQL_DATABASE: "quiz_db"
    volumes:
      - db-data:/var/lib/mysql
      - ./exam_portal.sql:/docker-entrypoint-initdb.d/exam_portal.sql

  # 2. Backend Spring Boot
  backend-api:
    image: zuza2828/quiz-backend:latest
    container_name: quiz-backend-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-db:3306/quiz_db"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "bardzo_silne_haslo_123"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
    depends_on:
      - mysql-db

  # 3. Frontend Angular / Nginx
  frontend-app:
    image: zuza2828/quiz-frontend:latest
    container_name: quiz-frontend-app
    ports:
      - "80:80"
    depends_on:
      - backend-api

volumes:
  db-data:
