version: '3.8'

services:
  # 1. Serwis Bazy Danych (MySQL)
  mysql-db:
    image: mysql:8.0
    container_name: quiz-mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "bardzo_silne_haslo_123"
      MYSQL_DATABASE: "quiz_db"
    volumes:
      - db-data:/var/lib/mysql
      - ./exam_portal.sql:/docker-entrypoint-initdb.d/exam_portal.sql

  # 2. Serwis Backendu (Spring Boot)
  backend-api:
    container_name: quiz-backend-api
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-db:3306/quiz_db"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "bardzo_silne_haslo_123"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"

    depends_on:
      - mysql-db

  # 3. Serwis Frontendu (Angular/Nginx)
  frontend-app:
    container_name: quiz-frontend-app
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend-api

volumes:
  db-data: